/**
 * A step's `adds` names the ingredients that go in during that step, in the
 * order they go in; each one becomes a band whose hue is the ingredient's role
 * and whose thickness is its amount. `moments` are the attention points that
 * bloom on the print. A side `timer` carries its own `adds` for the inner ring.
 */
export const recipes = [
  {
    id: "cacio-e-pepe",
    name: "Cacio e Pepe",
    lede: "Roman emulsion. Pepper, pecorino, eighteen minutes.",
    yield: "2 plates",
    totalSeconds: 18 * 60,
    palette: {
      paper: "#f3ead6",
      ink: "#241c14",
      mute: "#8a7b68",
      cream: "#fff6e4",
      soot: "#1b1611",
    },
    ingredients: [
      { name: "tonnarelli", grams: 250, role: "starch" },
      { name: "pecorino romano", grams: 90, role: "dairy" },
      { name: "black pepper", grams: 6, role: "spice" },
      { name: "pasta water", grams: 120, role: "liquid" },
      { name: "water", grams: 3000, role: "liquid" },
      { name: "salt", grams: 18, role: "mineral" },
    ],
    steps: [
      {
        id: "boil",
        title: "Boil a well of water",
        body: "Salt it until it tastes like the sea. Keep a mug for the starch later.",
        durationSec: 6 * 60,
        kind: "prep",
        heatC: 100,
        adds: ["water", "salt"],
      },
      {
        id: "pasta",
        title: "Cook the tonnarelli",
        body: "Two minutes shy of the box. Fish it out dripping.",
        durationSec: 9 * 60,
        kind: "cook",
        heatC: 98,
        adds: ["tonnarelli"],
        moments: [{ at: 7 * 60, note: "Taste. Keep a mug of the water." }],
      },
      {
        id: "emulsion",
        title: "Crash the emulsion",
        body: "Pepper first, then cheese, then a ribbon of water. Toss off the heat until it shines.",
        durationSec: 3 * 60,
        kind: "finish",
        heatC: 70,
        adds: ["pecorino romano", "pasta water", "black pepper"],
        moments: [{ at: 0, note: "Off the heat. Pepper, cheese, water.", big: true }],
      },
    ],
  },
  {
    id: "sunday-bolognese",
    name: "Sunday Bolognese",
    lede: "A pot that works while the house does nothing. Three hours.",
    yield: "6 bowls",
    totalSeconds: 3 * 60 * 60,
    palette: {
      paper: "#efe2cf",
      ink: "#2a1812",
      mute: "#7d6554",
      cream: "#f7e8d0",
      soot: "#1a100c",
    },
    ingredients: [
      { name: "beef mince", grams: 400, role: "protein" },
      { name: "pork mince", grams: 250, role: "protein" },
      { name: "onion", grams: 120, role: "aromatic" },
      { name: "carrot", grams: 80, role: "aromatic" },
      { name: "celery", grams: 80, role: "aromatic" },
      { name: "tomato passata", grams: 400, role: "acid" },
      { name: "whole milk", grams: 200, role: "dairy" },
      { name: "red wine", grams: 180, role: "liquid" },
      { name: "olive oil", grams: 30, role: "fat" },
      { name: "nutmeg", grams: 1, role: "spice" },
    ],
    steps: [
      {
        id: "soffritto",
        title: "Sweat the soffritto",
        body: "Onion, carrot, celery in oil until sweet, never brown.",
        durationSec: 15 * 60,
        kind: "prep",
        heatC: 140,
        adds: ["olive oil", "onion", "carrot", "celery"],
      },
      {
        id: "brown",
        title: "Brown the meats",
        body: "Raise the heat. Let the mince take colour before you stir.",
        durationSec: 12 * 60,
        kind: "cook",
        heatC: 190,
        adds: ["beef mince", "pork mince"],
        moments: [{ at: 0, note: "Raise the heat. Do not stir yet.", big: true }],
      },
      {
        id: "wine-milk",
        title: "Wine, then milk",
        body: "Wine down to a glaze. Milk until the pot looks pale and calm.",
        durationSec: 20 * 60,
        kind: "cook",
        heatC: 120,
        adds: ["red wine", "whole milk"],
        moments: [{ at: 10 * 60, note: "Wine is a glaze. Milk in." }],
      },
      {
        id: "simmer",
        title: "Tomato, lid ajar",
        body: "A lazy blip for the afternoon. Stir when you walk past.",
        durationSec: 123 * 60,
        kind: "simmer",
        heatC: 95,
        adds: ["tomato passata", "nutmeg"],
        moments: [{ at: 0, note: "Tomato in. Lid ajar." }],
      },
      {
        id: "rest",
        title: "Rest the pot",
        body: "Off the heat. The sauce settles and the fat rises to be skimmed or kept.",
        durationSec: 10 * 60,
        kind: "rest",
        heatC: 60,
        adds: [],
      },
    ],
  },
  {
    id: "roast-supper",
    name: "Roast supper",
    lede: "Chicken and a tray of vegetables on overlapping clocks.",
    yield: "4 plates",
    totalSeconds: 70 * 60,
    palette: {
      paper: "#f0e4cc",
      ink: "#261910",
      mute: "#8b7358",
      cream: "#fff3d8",
      soot: "#16110c",
    },
    ingredients: [
      { name: "whole chicken", grams: 1600, role: "protein" },
      { name: "potatoes", grams: 800, role: "starch" },
      { name: "carrots", grams: 400, role: "aromatic" },
      { name: "red onion", grams: 200, role: "aromatic" },
      { name: "olive oil", grams: 40, role: "fat" },
      { name: "thyme", grams: 4, role: "spice" },
      { name: "lemon", grams: 60, role: "acid" },
      { name: "butter", grams: 40, role: "dairy" },
      { name: "salt", grams: 12, role: "mineral" },
    ],
    steps: [
      {
        id: "heat",
        title: "Heat the oven, salt the bird",
        body: "220 °C. Dry the skin. Salt under and over.",
        durationSec: 12 * 60,
        kind: "prep",
        heatC: 220,
        adds: ["salt"],
      },
      {
        id: "roast",
        title: "Chicken in the oven",
        body: "Breast up. Vegetables join later on their own timer.",
        durationSec: 50 * 60,
        kind: "cook",
        heatC: 220,
        adds: ["whole chicken", "butter", "lemon", "thyme"],
        moments: [
          { at: 0, note: "Bird in, breast up.", big: true },
          { at: 15 * 60, note: "Tray of vegetables in beside it." },
        ],
        timers: [
          {
            id: "veg",
            label: "Tray of vegetables",
            durationSec: 35 * 60,
            offsetSec: 15 * 60,
            adds: ["potatoes", "carrots", "red onion", "olive oil"],
          },
        ],
      },
      {
        id: "rest-carve",
        title: "Rest, then carve",
        body: "Eight quiet minutes. The tray stays hot for the juices.",
        durationSec: 8 * 60,
        kind: "rest",
        heatC: 70,
        adds: [],
        moments: [{ at: 0, note: "Out. Rest under foil." }],
      },
    ],
  },
];

export function recipeById(id) {
  return recipes.find((recipe) => recipe.id === id) ?? recipes[0];
}
