export const recipes = [
  {
    id: "cacio-e-pepe",
    name: "Cacio e Pepe",
    lede: "Roman emulsion. Pepper, pecorino, eighteen minutes.",
    yield: "2 plates",
    totalSeconds: 18 * 60,
    palette: {
      paper: "#f3ead6",
      ink: "#241c14",
      mute: "#8a7b68",
      tomato: "#b42318",
      olive: "#5a5a32",
      gold: "#c9a15b",
      cream: "#fff6e4",
      soot: "#1b1611",
    },
    ingredients: [
      { name: "tonnarelli", grams: 250, role: "starch" },
      { name: "pecorino romano", grams: 90, role: "dairy" },
      { name: "black pepper", grams: 6, role: "spice" },
      { name: "pasta water", grams: 120, role: "liquid" },
      { name: "salt", grams: 18, role: "mineral" },
    ],
    steps: [
      {
        id: "boil",
        title: "Boil a well of water",
        body: "Salt it until it tastes like the sea. Keep a mug for the starch later.",
        durationSec: 6 * 60,
        kind: "prep",
        heatC: 100,
      },
      {
        id: "pasta",
        title: "Cook the tonnarelli",
        body: "Two minutes shy of the box. Fish it out dripping.",
        durationSec: 9 * 60,
        kind: "cook",
        heatC: 98,
      },
      {
        id: "emulsion",
        title: "Crash the emulsion",
        body: "Pepper first, then cheese, then a ribbon of water. Toss off the heat until it shines.",
        durationSec: 3 * 60,
        kind: "finish",
        heatC: 70,
      },
    ],
  },
  {
    id: "sunday-bolognese",
    name: "Sunday Bolognese",
    lede: "A pot that works while the house does nothing. Three hours.",
    yield: "6 bowls",
    totalSeconds: 3 * 60 * 60,
    palette: {
      paper: "#efe2cf",
      ink: "#2a1812",
      mute: "#7d6554",
      tomato: "#9c1f16",
      olive: "#4a5528",
      gold: "#b8893a",
      cream: "#f7e8d0",
      soot: "#1a100c",
    },
    ingredients: [
      { name: "beef mince", grams: 400, role: "protein" },
      { name: "pork mince", grams: 250, role: "protein" },
      { name: "onion", grams: 120, role: "aromatic" },
      { name: "carrot", grams: 80, role: "aromatic" },
      { name: "celery", grams: 80, role: "aromatic" },
      { name: "tomato passata", grams: 400, role: "acid" },
      { name: "whole milk", grams: 200, role: "dairy" },
      { name: "red wine", grams: 180, role: "liquid" },
      { name: "olive oil", grams: 30, role: "fat" },
      { name: "nutmeg", grams: 1, role: "spice" },
    ],
    steps: [
      {
        id: "soffritto",
        title: "Sweat the soffritto",
        body: "Onion, carrot, celery in oil until sweet, never brown.",
        durationSec: 15 * 60,
        kind: "prep",
        heatC: 140,
      },
      {
        id: "brown",
        title: "Brown the meats",
        body: "Raise the heat. Let the mince take colour before you stir.",
        durationSec: 12 * 60,
        kind: "cook",
        heatC: 190,
      },
      {
        id: "wine-milk",
        title: "Wine, then milk",
        body: "Wine down to a glaze. Milk until the pot looks pale and calm.",
        durationSec: 20 * 60,
        kind: "cook",
        heatC: 120,
      },
      {
        id: "simmer",
        title: "Tomato, lid ajar",
        body: "A lazy blip for the afternoon. Stir when you walk past.",
        durationSec: 150 * 60,
        kind: "simmer",
        heatC: 95,
      },
      {
        id: "rest",
        title: "Rest the pot",
        body: "Off the heat. The sauce settles and the fat rises to be skimmed or kept.",
        durationSec: 10 * 60,
        kind: "rest",
        heatC: 60,
      },
    ],
  },
  {
    id: "roast-supper",
    name: "Roast supper",
    lede: "Chicken and a tray of vegetables on overlapping clocks.",
    yield: "4 plates",
    totalSeconds: 70 * 60,
    palette: {
      paper: "#f0e4cc",
      ink: "#261910",
      mute: "#8b7358",
      tomato: "#a33a1c",
      olive: "#3f4a24",
      gold: "#d2a24a",
      cream: "#fff3d8",
      soot: "#16110c",
    },
    ingredients: [
      { name: "whole chicken", grams: 1600, role: "protein" },
      { name: "potatoes", grams: 800, role: "starch" },
      { name: "carrots", grams: 400, role: "aromatic" },
      { name: "red onion", grams: 200, role: "aromatic" },
      { name: "olive oil", grams: 40, role: "fat" },
      { name: "thyme", grams: 4, role: "spice" },
      { name: "lemon", grams: 60, role: "acid" },
      { name: "butter", grams: 40, role: "dairy" },
    ],
    steps: [
      {
        id: "heat",
        title: "Heat the oven, salt the bird",
        body: "220 °C. Dry the skin. Salt under and over.",
        durationSec: 12 * 60,
        kind: "prep",
        heatC: 20,
      },
      {
        id: "roast",
        title: "Chicken in the oven",
        body: "Breast up. Vegetables join later on their own timer.",
        durationSec: 50 * 60,
        kind: "cook",
        heatC: 220,
        timers: [
          {
            id: "veg",
            label: "Tray of vegetables",
            durationSec: 35 * 60,
            offsetSec: 15 * 60,
          },
        ],
      },
      {
        id: "rest-carve",
        title: "Rest, then carve",
        body: "Eight quiet minutes. The tray stays hot for the juices.",
        durationSec: 8 * 60,
        kind: "rest",
        heatC: 70,
      },
    ],
  },
];

export function recipeById(id) {
  return recipes.find((recipe) => recipe.id === id) ?? recipes[0];
}
